Perl make_deps

diff --git a/build/make_deps b/build/make_deps
--- a/build/make_deps
+++ b/build/make_deps
@@ -1,37 +1,40 @@
-#!/bin/bash
+#!/usr/bin/perl -Tw
 
-# $Id$ 
+# $Id$
 
-UPRFILE=src/uk.co.terryburton.bwipp.upr
+use strict;
 
-PSFILE=$1
-shift
+my $srcfile=shift @ARGV || '';
 
-if [ ! -f "$PSFILE" ]; then
-  echo "File not found: $PSFILE"
-  exit 1
-fi
+open(SRC,$srcfile) || die "Unable to open source file: $srcfile";
+my $src=join('',<SRC>);
+close(SRC);
 
-PROVIDES=`sed -n -e 's/^% --BEGIN \([^ ]*\) \(.*\)--$/\2/p' $PSFILE`
-if [ "$PROVIDES" == "preamble" ]; then
-  PROVIDES="uk.co.terryburton.bwipp"
-fi
+open(UPR,'src/uk.co.terryburton.bwipp.upr') || die 'Unable to open UPR file';
+my $upr=join('',<UPR>);
+close(UPR);
 
-PROVFILE=`sed -n -e "s/^$PROVIDES=//p" $UPRFILE`
-RESOURCES=`sed -n -e 's/^% --REQUIRES \(.*\)--$/\1/p' $PSFILE`
+(my $begin, $_, my $resource, my $meta, $_, my $end)=$src=~/
+  (^%\ --BEGIN\ (ENCODER|RENDERER|RESOURCE)\ ([\w-]+?)--$)
+  (.*?)
+  (^[^%].*?)
+  (^%\ --END\ \2\ \3--$)
+/msgx;
 
-for TARGETDIR in $@; do
+$resource='uk.co.terryburton.bwipp' if $resource eq 'preamble';
 
-  RESFILES="$TARGETDIR/$PROVFILE : "
-  for RESOURCE in $RESOURCES; do
-    if [ "$RESOURCE" == "preamble" ]; then
-      RESOURCE="uk.co.terryburton.bwipp"
-    fi
-    RESFILE=`sed -n -e "s/^$RESOURCE=//p" $UPRFILE`
-    RESFILES="$RESFILES $TARGETDIR/$RESFILE"
-  done
+(my $reqs)=$meta=~/^% --REQUIRES (.*)--$/mg;
+$reqs='' unless defined $reqs;
 
-  echo $RESFILES
+(my $provfile)=$upr=~/^$resource=(.*)$/m;
 
-done 
+while (my $targetdir=shift @ARGV) {
+  my $reqfiles="$targetdir/$provfile : ";
+  foreach my $req (split /\s+/, $reqs) {
+    $req='uk.co.terryburton.bwipp' if $req eq 'preamble';
+    (my $reqfile)=$upr=~/^$req=(.*)$/m;
+    $reqfiles.="$targetdir/$reqfile ";
+  }
+  print "$reqfiles\n";
+}
 
